name: BlazeRunner Test
on:
    workflow_call:
    workflow_dispatch: 
jobs:
  Blaze:
    runs-on: ubuntu-latest
    steps:
        - name: BlazeRunnerAction
          uses: Blazemeter/github-action@v8.2
          with:
            # API Key
            apiKey: '4dcf796c060c0f3d20c9fa19'
            # API Secret
            apiSecret: '2d3885d7aa1a6b8b740629b70284843f302b4f13d5c67081c77b9b80b73277012da72c0e'
            # Test ID
            testID: 1
            # Test name for creating new test
            testName: performance
            createTest: true
            projectID: '2247099'
            inputAllFiles: true
            uploadFileCheck: true
            
