name: BlazeRunner Test
on:
    workflow_call:
        inputs:
          testID:
            required: true
            type: string
          masterID:
            required: true
            type: string
        
    workflow_dispatch: 
jobs:
  Blaze:
    runs-on: ubuntu-latest
    environment: 
        name: 'production'
        url: 'https://a.blazemeter.com/app/executive-summary/index.html?master_id=${{inputs.masterID}}&selectedTimeMeasure=milliseconds#/'
    steps:
        - name: Create Test
          run: |
            curl 'https://a.blazemeter.com/api/v4/tests/${{inputs.testID}}/start?delayedStart=false' \
            -X POST \
            -H 'Content-Type: application/json' \
            --user '${{secrets.BZM_KEY}}:${{secrets.BZM_SECERET}}'
        - run: sleep 300