name: BlazeRunner Test
on:
    workflow_call:
    workflow_dispatch: 
jobs:
  Blaze:
    runs-on: ubuntu-latest
    steps:
        - name: BlazeRunnerAction
          uses: Blazemeter/github-action@v8.2
          with:
            # API Key
            apiKey:  ${{secrets.BZM_KEY}}
            # API Secret
            apiSecret: ${{secrets.BZM_SECERET}}
            # Test ID
            testID: '13761540'
            createTest: true
            