name: .NET Build & Run

on:
  push:
    branches: [ feature/app ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: dotnet-app

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: dotnet-app

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: dotnet-app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: dotnet-app/publish

    - name: Run
      run: dotnet run
      working-directory: dotnet-app
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Production'
      url: ${{steps.deploy-to-web.outputs.webapp-url}}
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: application
        path: application

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-web
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnetappgithubactions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET }}
        package: application
