name: .NET Build & Run

on:
  push:
    branches: [ 'feature/app' ] # specify your branch name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ${{github.workspace}}/dotnet-app/
       
    - name: Build
      run: dotnet build --configuration Release --no-restore ${{github.workspace}}/dotnet-app/

    - name: Publish
      run: dotnet publish --configuration Release --output publish ${{github.workspace}}/dotnet-app/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: ${{github.workspace}}/dotnet-app/publish/*
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Production'
      url: ${{steps.deploy-to-web.outputs.webapp-url}}
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: application
        path: application

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-web
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnetappgithubactions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET }}
        package: application
