name: Deploy ASP.NET MVC App deploy to Azure Web App
# build using template
on:
  workflow_dispatch:  
  push:
    branches: 
      - feature/app
env:
  AZURE_WEBAPP_NAME: dotnetappgithubactions    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build-scan:
    uses: rajkumar-r-org/build-template/.github/workflows/rajkumar-assignment3.yml@main
    secrets: 
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      token_git: ${{secrets.TOKEN_GITHUB}}

  deploy:
    needs: build-scan
    name: DEV
    uses: rajkumar-r-org/build-template/.github/workflows/deploy-azurewebapp.yml@main    
    with:
      AZURE_WEBAPP_NAME: 'dotnetappgithubactions'
      AZURE_WEBAPP_PACKAGE_PATH: './'

    secrets:
      web-app-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET}}