name: .NET Build & Deploy

on:
  workflow_dispatch: 
  # push:
  #   branches: [ feature/app ]
  # pull_request:
  #   branches: [ feature/app ]

env:
  AZURE_WEBAPP_NAME: dotnetappgithubactions
  AZURE_WEBAPP_PACKAGE_PATH: "."
  # jira_url: 'rajkumar-r'
  # jira_usermail: 'rajkumarravi21897@gmail.com'

jobs:
  SonarScan:
    uses: rajkumar-r-org/build-template/.github/workflows/sonar-analysis.yml@main
    name: SonarScan
    secrets: inherit
    with:
      organization: 'rajkumar-org'
      projectKey: 'rajkumar-r-org_dotnet-app'

  CodeQL:
    uses: rajkumar-r-org/build-template/.github/workflows/codeql-analysis.yml@main
    name: CodeQL
    permissions:
      actions: read
      security-events: write
      contents: read

  Create_Issue:
    uses: rajkumar-r-org/build-template/.github/workflows/Create-Issue-Jira.yml@main
    needs: [SonarScan,CodeQL]
    secrets: inherit
    name: JIRA-ISSUE
    
    with:
      JIRA_BASE_URL: ${{vars.JIRA_URL}}
      JIRA_USER: ${{vars.JIRA_USERMAIL}}
       
  Build_Test:
    name: Build
    if: needs.Create_Issue.outputs.status == 'OK'
    needs : [Create_Issue] # Ensure that the Build job is completed before starting the Test job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal

    - name: Publish
      run:  dotnet publish -c Release -o ./myapp
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: 'webapp-artifact'
        path: ./myapp

  
  Deploy-DEV :
    needs: Build_Test # Ensure that the  job is completed before starting the Test job
    runs-on : ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp-dev.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: 'webapp-artifact'
          path: './'
        
      - name: Deploy to DEV
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'DEV'
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET_DEV}}

  Dev-Blaze-Test:
    needs: Deploy-DEV
    uses: rajkumar-r-org/build-template/.github/workflows/blazescan.yml@main
    name: blaze-dev-test
    secrets: inherit
    with:
      testID: '13763443'
      masterID: '70999404'

  Deploy-QA :
    needs: [Deploy-DEV, Dev-Blaze-Test] # Ensure that the  job is completed before starting the Test job
    runs-on : ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp-qa.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: 'webapp-artifact'
          path: './'
        
      - name: Deploy to QA
        id: deploy-to-webapp-qa
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'QA'
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET_QA}}

  QA-Blaze-Test:
    needs: Deploy-QA
    uses: rajkumar-r-org/build-template/.github/workflows/blazescan.yml@main
    name: blaze-qa-test
    secrets: inherit
    with:
      testID: '13763444'
      masterID: '70999426'

  Deploy-PROD :
    needs: [Deploy-QA, QA-Blaze-Test] # Ensure that the  job is completed before starting the Test job
    runs-on : ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp-prod.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: 'webapp-artifact'
        path: './'
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp-prod
      uses: azure/webapps-deploy@v2
      with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET}}

  PROD-Blaze-Test:
    needs: Deploy-PROD
    uses: rajkumar-r-org/build-template/.github/workflows/blazescan.yml@main
    name: blaze-prod-test
    secrets: inherit
    with:
      testID: '13761540'
      masterID: '70998982'
