name: SonarScan

on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
        default: 'rajkumar-org'
      projectKey:
        required: true
        type: string
        default: 'rajkumar-r-org_dotnet-app'
      sources:
        required: true
        type: string
        default: './dotnet-app/'

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: dotnet-app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: >
          -Dsonar.organization= ${{inputs.organization}}
          -Dsonar.projectKey= ${{inputs.projectKey}}
          -Dsonar.sources=${{inputs.sources}}
          -Dsonar.tests=${{inputs.sources}}tests/
          -Dsonar.verbose=true