name: path test

on:
  workflow_dispatch:
  push:
    branches: feature/app


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: path
        run: |
          echo ${{github.workspace}}
          echo ${{github.workspace}}/.github/
          ls ${{github.workspace}}/.github/
  
  
    
